### ISSUE TITLE
Some URL normalization is not necessary on GitLab

### ISSUE THREAD

**Issue by eclipsewebmaster** [EclipseFdn/eclipsefdn-github-sync#124]
I had requested this repo: https://gitlab.eclipse.org/eclipse/dash/org.eclipse.dash.handbook

I got this repo: https://gitlab.eclipse.org/eclipse/dash/org-eclipse-dash-handbook (dashes instead of dots) 

The repo name contains dots, but the URLs and clone links contain dashes. 
https://gitlab.eclipse.org/eclipse/dash/org-eclipse-dash-handbook

This is not necessary.  Please allow dots.

**Comment by autumnfound** [comment]
This request is related to an issue filed on the Gitlab instance: https://gitlab.eclipse.org/eclipsefdn/gitlab/-/issues/21

I'll do some testing tomorrow. Are there any other characters we should allow? Right now I believe the sanitization requires Latin alphanumeric + dashes

**Comment by eclipsewebmaster** [comment]
Thanks!

**Comment by autumnfound** [comment]
I've tested periods and they work fine. Are there any other characters we want to add to the exception list?
