### ISSUE TITLE
Grant PL maintainer privilege as part of the sync rather than developer

### ISSUE THREAD

**Issue by autumnfound** [EclipseFdn/eclipsefdn-github-sync#143]
This was requested in the Gitlab project on our GL instance: https://gitlab.eclipse.org/eclipsefdn/gitlab/-/issues/17#note_256

**Comment by fredg02** [comment]
This does not seem to work yet, I've checked the permissions in several GitLab groups (APP4MC, AsciiDoc, Comma, Lsat, Eclipse SW360 and ESCET), but project leads do not have maintainer permissions.

**Comment by fredg02** [comment]
Fixed via #162 and #167.
