### ISSUE TITLE
Change release strategy to tagged release rather than rolling

### ISSUE THREAD

**Issue by autumnfound** [EclipseFdn/eclipsefdn-github-sync#154]
To provide better stability for builds, I'm suggesting we move away from a rolling release to a tagged release strategy. This would give us more control over when things go live without having them have to sit in a PR waiting for a stable time to be built.

@mbarbero @fredg02 @chrisguindon thoughts on this?

**Comment by mbarbero** [comment]
godspeed

**Comment by autumnfound** [comment]
I had a quick call with Mika over this, and he passed on that we should do this as we are doing it in open-vsx https://github.com/EclipseFdn/open-vsx.org/issues/391#issuecomment-787776288

Instead of tagged releases, we would make merge requests to a production branch that would be checked in the Jenkinsfile, and make a production build when finding that branch. I'll make a PR for this today!

**Comment by mbarbero** [comment]
Note that it does not prevent you from tagging commits if you want to have labels on "releases", but the tagging alone won't trigger any deployment.
