### ISSUE TITLE
Being added to the Eclipse Page 

### ISSUE THREAD

**Issue by HailleySeed** [EclipseFdn/eclipsefdn-github-sync#187]
Hi there,
I am the new virtual events specialist and would like to please be added the eclipsefdn staff team on Github. Here is the link! https://api.eclipse.org/account/profile/hailleyseed

Thank you,
Hailley

**Comment by chrisguindon** [comment]
@autumnfound Let's add @HailleySeed to our 3 orgs (eclipsefdn, jakartaee and openhwgroup).

Thanks

**Comment by chrisguindon** [comment]
@autumnfound Can you take a look at this... I don't see Hailey in our EclipseFdn org..

**Comment by chrisguindon** [comment]
@autumnfound Nevermind. I see her now, her invitation is still pending. It wasn't accepted yet.
