### ISSUE TITLE
Build failing on deploy to cluster step

### ISSUE THREAD

**Issue by autumnfound** [EclipseFdn/eclipsefdn-github-sync#197]
After cluster migration, pushed a fix to production branch, and the subsequent build failed: https://foundation.eclipse.org/ci/webdev/job/eclipsefdn-github-sync/job/production/28/console. This might be due to the previous credentials no longer being a valid set. @mbarbero WDYT?

**Comment by mbarbero** [comment]
Yep, I updated the Jenkinsfile but at a single location:

https://github.com/EclipseFdn/eclipsefdn-github-sync/blob/ea128fc335748a76fa9f624eff4a4154b7ef314f/Jenkinsfile#L111

but of course it must be propagated to 

https://github.com/EclipseFdn/eclipsefdn-github-sync/blob/ea128fc335748a76fa9f624eff4a4154b7ef314f/Jenkinsfile#L92
