### ISSUE TITLE
Ability to remove outside collaborators

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/eclipsefdn-github-sync#39]
We found a few outside collaborators with write access to some github repositories.

More often than not, these users are not committers on a project. I would like to propose that this sync script take on the responsibility for removing access to these users.

Basically, We must remove all outside collaborators not listed here:
https://api.eclipse.org/bots

**Comment by chrisguindon** [comment]
Additional clarifications:

We need to remove all users that are not bot at the organization and repository level!

**Comment by chrisguindon** [comment]
@autumnfound I am thinking that we should keep project leads and set their access role to maintainer. 

For now, I don't think we want to actively add PL to a repo but if webmaster manually grant them maintner access, the script should not remove them.

Is this something that we can do with octokit?

**Comment by autumnfound** [comment]
@chrisguindon In terms of ability to set a user as a maintainer, this is currently possible in the teams API, but isn't supported in the repo API, though they can have that permission set. An alternative is that we add PLs to all teams and set their permission to maintainer if we want to be able to manage this functionality end to end. 

If we are looking to just retain repo membership for PLs without changing the permissions, we can at least do that, but if things fall out of sync that can't be set.

**Comment by chrisguindon** [comment]
@autumnfound The maintain role would be at the repository level not the team API:
 https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization

Maintain: Recommended for project managers who need to manage the repository without access to sensitive or destructive actions

**Comment by chrisguindon** [comment]
Remember that the focus of this issue is on people that have access outside of a team.

**Comment by autumnfound** [comment]
@chrisguindon I think our phase 2 merge covers this. Are we good to close this issue?

**Comment by chrisguindon** [comment]
+1 I will open a new request (low priority) to remove users are in 0 teams.
