### ISSUE TITLE
Ability to remove users from specific github teams

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/eclipsefdn-github-sync#4]

**Comment by chrisguindon** [comment]
I propose that we fix this issue in two steps:

STEP 1: (priority)
We emulate the functionality of the previous script were we would remove users if we were able to validate their identity. The only change is that we should leverage our github account endpoint on api.eclipse.org to validate accounts.

I believe that we did that to keep our bots account in our committers teams:
https://github.com/EclipseFdn/eclipse-webhook/blob/master/bin/github_verify_committers.php#L156

Step 2:
Once our new https://github.com/EclipseFdn/projects-bots-api is on production, we should leverage it's data to synchronize bots account across our github organizations.

At this point, we should be able to remove the user account validation from Step 1.

This process should not remove users teams other than -committers and -contributors.

**Comment by autumnfound** [comment]
Phase 2 of this issue has been implemented and is live
