### ISSUE TITLE
Feature Request for GitHub Sync script - Give every project lead the maintainer role

### ISSUE THREAD

**Issue by fredg02** [EclipseFdn/eclipsefdn-github-sync#41]
Context:
GitHub added the "maintain" level/role a while ago (see also https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization).

It gives the user the following additional permissions:
* Edit a repository's description
* Manage topics
* Enable wikis and restrict wiki editors
* Enable project boards
* Configuring pull request merges
* Configuring a publishing source for "GitHub Pages"
* Push to protected branches
* Create and edit repository social cards
* Limit interactions in a repository

Giving project leads these permission _permanently_ can improve self-servicing and reduce overhead on webmaster's side without dangerous side effects.

This has been discussed here:
* https://bugs.eclipse.org/bugs/show_bug.cgi?id=533471
* https://bugs.eclipse.org/bugs/show_bug.cgi?id=487359#c9

It's also been tested in a few cases:
* https://bugs.eclipse.org/bugs/show_bug.cgi?id=549574
* https://bugs.eclipse.org/bugs/show_bug.cgi?id=547561
* https://bugs.eclipse.org/bugs/show_bug.cgi?id=553418

Copied from: https://bugs.eclipse.org/bugs/show_bug.cgi?id=559859

**Comment by chrisguindon** [comment]
@fredg02 it's seems that the only controversial permission here is that PL will now have access to "Push to protected branches".

I don't believe that the other permissions have a direct impact to the project source code.

@waynebeaton do you have any concerns here?

**Comment by autumnfound** [comment]
Currently there is no support in the GitHub API to set users with the `maintain` role on a repository. This is still in beta (or recently out of it) and hasn't hit all endpoints as an option to be set yet. The list of supported endpoints currently does not include the repository endpoint.

https://octokit.github.io/rest.js/#octokit-routes-repos-add-collaborator
https://developer.github.com/v3/repos/collaborators/#add-user-as-a-collaborator

If we were to add this permission for project leads, it would have to be maintained manually for the time being until the base GitHub API is updated

**Comment by chrisguindon** [comment]
Related issue:

- [Expose `triage` and `maintain` permissions #2041](https://github.com/octokit/octokit.net/issues/2041)

I see two topics here:
- Discuss if we should grant maintainer role to our PL
- How should we implement this if we decide to move forward with this initiative?

**Comment by chrisguindon** [comment]
> How should we implement this if we decide to move forward with this initiative?

A solution would be to allow webmaster to manually add users with maintain role and we alter the script to make sure that it does not remove a PL unless they have admin access.

**Comment by waynebeaton** [comment]
We have a meeting with some decision makers at GitHub next week. It would be helpful if you could summarize the problem briefly and describe as precisely as possible how GitHub could help us make this work. Start from the ideal and we'll work back to realistic.

**Comment by chrisguindon** [comment]
I would like to propose that we move forward with the proposal I made on https://bugs.eclipse.org/bugs/show_bug.cgi?id=487359#c56

We should start by creating a new "project-leads" team on github for each of our projects as we are doing for our contributors and our committers.

Initially, this new project-lead team will have "triage" access by default. They don't need write access since this is granted via the committer team.

This new team will give us the flexibility to manually change the access level from "triage" to "maintain" or "admin" based off the requirements from the request that was made by the project on bugzilla.

The responsibility of our github-sync-script will be to add or remove users from the project-leads team but the script will not try to change/revert the access level.

**Comment by fredg02** [comment]
Why should we not give "maintain" permissions to project-leads right from the start?

**Comment by autumnfound** [comment]
The `triage` permissions are in the same boat as `maintain` permissions. The only valid permissions are `push`, `pull`, and `admin`. Please see https://developer.github.com/v3/teams/#add-or-update-team-repository

**Comment by chrisguindon** [comment]
@autumnfound Thanks for reminding me :) Let's give them read access for now. If we ever decide that they should have admin access, we can update that later!

@fredg02 same problem as my comment, triage and maintain are not valid via the api!

**Comment by fredg02** [comment]
Ah OK. @autumnfound please try to force the triage/maintain permissions despite the fact that the API documentation does not describe it. Apparently the documentation is not always up to date (see https://github.community/t5/GitHub-API-Development-and/Update-Collaborator-Permission/m-p/43155 and https://github.community/t5/GitHub-API-Development-and/Triage-and-Maintain-roles-in-the-Collaborators-API/m-p/40865).
If it still does not work, then we should consider setting the maintain permission via the collaborator API (see https://developer.github.com/v3/repos/collaborators/#add-user-as-a-collaborator).

**Comment by chrisguindon** [comment]
@fredg02 please see: https://github.com/octokit/octokit.net/issues/2041#issuecomment-583859173

**Comment by autumnfound** [comment]
@fredg02 We tried again to be sure it wasn't implemented in the past couple of months since we last tested. We tried both `maintain` and `triage` but neither are working at this moment through the GitHub API.

**Comment by fredg02** [comment]
Thanks @chrisguindon & @autumnfound. Just to clarify, there are are a couple of issues with the GitHub API:
* It does not support setting triage and maintain permissions for *teams* AFAICT
* It does support *setting* triage and maintain permission for collaborators
* It does not *list* all permissions of collaborators (only admin, write, read, none)
* Checking the permission of collaborators can be done with GraphQL though.

So instead of creating a PL team, we could use the API directly (without Octokit) to add a PL with maintain permissions as collaborator. If absolutely necessary, we could use GraphQL to query permissions of collaborators.

It's a workaround, but it's still better than setting permissions manually, IMHO.

**Comment by chrisguindon** [comment]
> It's a workaround, but it's still better than setting permissions manually, IMHO.

For the moment, it was decided that elevated permission would only be granted if it was requested by the project.

**Comment by chrisguindon** [comment]
The sync script has created the new PL team!

As discussed, elevated permission will be granted by @eclipsewebmaster but project are required to open a bug and explain why they need admin access.

**Comment by eclipsewebmaster** [comment]
Support for maintain and triage permission is close: https://github.com/octokit/octokit.net/issues/2041#issuecomment-604311880 and following

**Comment by fredg02** [comment]
Support for maintain and triage permission is close: https://github.com/octokit/octokit.net/issues/2041#issuecomment-604311880 and following

**Comment by autumnfound** [comment]
THere will be a delay around getting this live as there is a major rewrite and retest effort with any new features. I'll start work once this is prioritised within context of other MBO's and tasks

**Comment by chrisguindon** [comment]
I am wondering if we could update our sync script to allow webmaster to set the triage team for contributors now that we can read those permissions.

This could be a temporary solution while we wait until we can update these roles via the api. Then we will want to give triage role to all our contributors.

**Comment by autumnfound** [comment]
@fredg02 right now, we have 'overwrite' set to false for updating PL permissions. If we leave this on, it means that none of the existing teams will get maintain unless manually set. If we set it to true, any admins would be set back to maintain. How do you want to handle this?

**Comment by fredg02** [comment]
I'd suggest to set the PL permissions to "maintain(er)" by default. If we manually set the PL permissions to "admin" this should not be overwritten.

**Comment by autumnfound** [comment]
Currently, it is the new default. The overwrite doesn't check what permission it would overwrite, it will just overwrite if overwrites are enabled. What this means for you is that we can leave it as is, and any existing teams would be updated manually on an as-requested basis, or we can turn on overwriting, and manually reapply admin-level access to anyone who had it. Which situation would you prefer?

**Comment by fredg02** [comment]
Is there an easy way to scan and filter out all PL teams that currently have admin permissions, so we can re-apply them manually?

**Comment by autumnfound** [comment]
Scan and filter? No, I'd have to write a script to scan all of our project teams which we currently don't have a report for.

**Comment by chrisguindon** [comment]
How about we keep the current state for the existing PL team and moving forward, we simply create a new PL team with the maintainer permission?

The existing PL team will have to request this change via Bugzilla > Github. 

I think we are good with granting "triage" to all our collaborator teams.

Does this work for you @fredg02 ?

**Comment by fredg02** [comment]
I managed to query the API to get a list of *-project-leads teams that have the admin permission set. So we should be good to go to set all PL teams to 'maintain' permissions with the sync-script. Once that is done, I can manually set the admin permissions for the teams that had it before (only 4 teams by my count). Let's discuss this tomorrow, before we run this.

**Comment by chrisguindon** [comment]
@fredg02 I will schedule a quick call tomorrow with you, me, and @autumnfound to discuss these final details!

**Comment by autumnfound** [comment]
This was merged in last week and is stable. We can reopen this to track the remaining admin teams if you like, I just didn't want to leave this hanging.
