### ISSUE TITLE
Second job needed for running GitLab sync

### ISSUE THREAD

**Issue by autumnfound** [EclipseFdn/eclipsefdn-github-sync#42]
As part of the development of the sync script, a new job needs to be created to run this script. Ideally, this would be done in parallel with the already running GitHub script to not add further processing time on the single VM and potentially increasing time between jobs. It would be best if this script ran independently of the GitHub script completely, to ensure errors in one script does not impact the other.

**Comment by autumnfound** [comment]
@mbarbero do you have any insight on if this is possible, or if there might be a better way to manage multiple jobs/pods?

**Comment by mbarbero** [comment]
Fully agree, it should be a different cronjob from https://github.com/EclipseFdn/eclipsefdn-github-sync/blob/master/k8s/cronjob.yml

**Comment by autumnfound** [comment]
This is live and running
