### ISSUE TITLE
Do not reset contributor team's permissions if it's set to "triage"

### ISSUE THREAD

**Issue by fredg02** [EclipseFdn/eclipsefdn-github-sync#50]
Once the GitHub API allows to check for the "triage" permission, the sync script should not reset a contributor team's permissions.

See https://bugs.eclipse.org/bugs/show_bug.cgi?id=562071

**Comment by autumnfound** [comment]
https://github.com/EclipseFdn/eclipsefdn-github-sync/issues/41#issuecomment-614743516

This is possible, but would require some logic updates to the part of the script that checks whether a group should be updated

**Comment by autumnfound** [comment]
Also to be clear, this functionality does not yet exist and this enhancement is currently on hold. Work will start on this enhancement when the check has been implemented in the Git API and we update to the new breaking version.

**Comment by DanHeidinga** [comment]
Reading https://github.com/octokit/octokit.net/issues/2041#issuecomment-610632363, it seems like the Github api has been updated to return the triage permission.

Is this enhancement still on hold?

**Comment by fredg02** [comment]
> Reading [octokit/octokit.net#2041 (comment)](https://github.com/octokit/octokit.net/issues/2041#issuecomment-610632363), it seems like the Github api has been updated to return the triage permission.
> 
> Is this enhancement still on hold?

Yes, it's still on hold, since the GitHub API supports it, but it has not been added to octokit.net (the client API library that we are using). See also https://github.com/octokit/octokit.net/releases.

**Comment by DanHeidinga** [comment]
Thanks @fredg02.  Have octokit indicated when it will be added to their library?  I'd like to set the OpenJ9 communities expectations on when this might be available.

**Comment by fredg02** [comment]
> Thanks @fredg02. Have octokit indicated when it will be added to their library? I'd like to set the OpenJ9 communities expectations on when this might be available.

I've commented on the issue. You can see the reply here: https://github.com/octokit/octokit.net/issues/2041#issuecomment-634608936

**Comment by chrisguindon** [comment]
@autumnfound Can you verify if this was implemented in https://github.com/octokit/rest.js? If not, let's make sure that we create an issue for this.

**Comment by autumnfound** [comment]
It looks as though this feature is present in Octokit REST.js, in at the very least version 18 of the product. Once we update to the newest version we should have this functionality ready and configurable then.

**Comment by autumnfound** [comment]
@fredg02 @chrisguindon do we want to set the contributors permissions to 'triage' going forward? In testing another feature, I was able to confirm that the recent update to the version of octokit we use has enabled setting the triage permission.

**Comment by autumnfound** [comment]
Actually a follow up to this, since the fix for #41 will set all contributor teams to have triage permissions, can we close this issue?

**Comment by chrisguindon** [comment]
Why is that the fix for #41? The feature that @fredg02 is requesting there is to Give every PL the maintainer role, not contributors.

The request here is to keep the triage role but the default should be read in my opinion.

This is how I am understanding both requests, am I missing something?

**Comment by chrisguindon** [comment]
> @fredg02 @chrisguindon do we want to set the contributors permissions to 'triage' going forward? In testing another feature, I was able to confirm that the recent update to the version of octokit we use has enabled setting the triage permission.

-1 I don't want to give contributors more access unless the project asks for it.

**Comment by fredg02** [comment]
The purpose of this issue was **to not reset** the triage permission if it was set manually for a committer.

Since demands for triage permissions have been rare (so far), I agree with @chrisguindon to only set them on request.

**Comment by fredg02** [comment]
> Actually a follow up to this, since the fix for #41 will set all contributor teams to have triage permissions, can we close this issue?

#41 is discussing the maintainer permissions for project leads. Did you mean a different issue?

**Comment by DanHeidinga** [comment]
Now that this is implemented, how do we request contributor teams get the triage bit set?  (ie: https://bugs.eclipse.org/bugs/show_bug.cgi?id=562071)

**Comment by autumnfound** [comment]
I've added a PR that flips this, but Fred and I are discussing how to move forward as there are some logistics around updates to set a new default for PLs. We're hoping to have this live soon, so don't worry we haven't forgotten!

**Comment by fredg02** [comment]
@DanHeidinga Triage permissions can be requested through Bugzilla issues. You've already requested this in https://bugs.eclipse.org/bugs/show_bug.cgi?id=562071. Let's continue the discussion over there.

**Comment by chrisguindon** [comment]
This is what I think we want for this issue:

1. New collaborators teams are created with "read" access by default
2. Webmaster has the access to change that role to "triage" via Github UI.
3. Sync script must reset the access level to read if the access level is not "read" or "triage".

**Comment by fredg02** [comment]
@chrisguindon :+1:  LGTM

**Comment by chrisguindon** [comment]
@waynebeaton,

After a conversation with @autumnfound @fdesbiens and myself, we decided to propose that we the default permission level for every Collaborator team. 

These teams currently have READ permission. My next screenshot is a list of actions that collaborators will be able to do if we move forward with this change:

![Screen Shot 2020-09-25 at 2 20 30 PM](https://user-images.githubusercontent.com/893942/94302573-6cfe1b80-ff3a-11ea-9f5b-efca33201ea9.png)

Our questions to you are:

1. Do you have any objections?
2. Assuming you are on board with this change, would you recommend that we send a notice out in advance to our project before we roll this out?

**Comment by waynebeaton** [comment]
+1

For completeness, my only concern is intellectual property integrity. Specifically, it must be possible to trace every commit back to a project committer or a contributor who has signed the ECA; and only project committers can accept pull requests.
