### ISSUE TITLE
Update user creation to set users correct email rather than dummy address

### ISSUE THREAD

**Issue by autumnfound** [EclipseFdn/eclipsefdn-github-sync#56]
GitLab script currently sets new users to use a dummy email account for purposes of creation. While this is updated on the first login, users would not be notified of new requests made before that login. To fix this, an access token should be passed as authentication to retrieve the email address when fetching user information (this info is normally hidden due to GDPR).

**Comment by autumnfound** [comment]
@chrisguindon is this still needed? We've updated the dummy address to be a standard format that would follow a noreply email address once/if that functionality is added.

**Comment by chrisguindon** [comment]
This is still needed and should be added to your priority list. I would like to get this done in the next 2 weeks if possible.

**Comment by chrisguindon** [comment]
I think we are done here!

Closing.
